### ISSUE TITLE
MissingMethodException on selenium 2.48.0 and appium 1.4.0.3

### ISSUE THREAD

**Issue by randersen** [appium/appium-dotnet-driver#112]
Steps to reproduce

1. Upgrade selenium and support class nuget packages to 2.48.0
2. Upgrade Appium to 1.4.0.3
3. Instantiate a new IOSDriver<AppiumWebElement> or AndroidDriver<AppiumWebElement>

Notice the following exception in VS
```
An exception of type 'System.MissingMethodException' occurred in appium-dotnet-driver.dll but was not handled in user code

Additional information: Method not found: 'OpenQA.Selenium.Remote.CommandInfoRepository OpenQA.Selenium.Remote.CommandInfoRepository.get_Instance()'.
```

After a little digging i found the line the exception is being thrown on in appium-dotnet-driver is _AddAppiumCommands(); on line 82 of appiumDriver

Last line in appium console before exception
```
info: <-- GET /wd/hub/session/f84ddd45-88d6-4785-8cae-d7f7b79613f2 200 3.741 ms - 938 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"appium-version":"1.4.11","platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 6s","command-timeout":"90","launch-timeout":"120000","app":"/Users/ryananderson/Library/Developer/Xcode/DerivedData/Jane_iOS-dstkmwcscgkltneqrqyhmhdiessq/Build/Products/Debug-iphonesimulator/Jane iOS.app","name":"ios - actions"},"appium-version":"1.4.11","platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 6s","command-timeout":"90","launch-timeout":"120000","app":"/Users/ryananderson/Library/Developer/Xcode/DerivedData/Jane_iOS-dstkmwcscgkltneqrqyhmhdiessq/Build/Products/Debug-iphonesimulator/Jane iOS.app","name":"ios - actions"},"sessionId":"f84ddd45-88d6-4785-8cae-d7f7b79613f2"}
```

**Comment by randersen** [comment]
Also worth nothing that as a workaround if you downgrade to selenium 2.47.0 it works.

**Comment by Astro03** [comment]
line 82 calls a method in that same class, can you tell me exactly where the stack trace is showing?

thanks

**Comment by randersen** [comment]
I'm having trouble getting the debugger to step into that method. I'm not sure I'll be able to give any further detail on it.

**Comment by Astro03** [comment]
can you print the full stack trace  though?

**Comment by TikhomirovSergey** [comment]
Maybe there is a comflict. We use 2.47.0 by default. I think we need to upgrade the upstream and actualize sources.

**Comment by drewbrend** [comment]
I just ran into this issue as well after cloning the latest appium and selenium straight from their repos (trying to debug a different issue I am having).

I'm also having an issue stepping into the _AddAppiumCommands() method and I'm not sure why, I can clearly see the method.

Here's the error and stacktrace I'm seeing, hope this helps.

MissingMethodException was unhandled

Method not found: 'OpenQA.Selenium.Remote.CommandInfoRepository OpenQA.Selenium.Remote.CommandInfoRepository.get_Instance()'.

   at OpenQA.Selenium.Appium.AppiumDriver`1._AddAppiumCommands()
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) in c:\AppiumSource\appium-dotnet-driver\appium-dotnet-driver\Appium\AppiumDriver.cs:line 82
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout) in c:\AppiumSource\appium-dotnet-driver\appium-dotnet-driver\Appium\AppiumDriver.cs:line 112
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) in c:\AppiumSource\appium-dotnet-driver\appium-dotnet-driver\Appium\AppiumDriver.cs:line 101
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(ICapabilities desiredCapabilities) in c:\AppiumSource\appium-dotnet-driver\appium-dotnet-driver\Appium\AppiumDriver.cs:line 91
   at OpenQA.Selenium.Appium.Android.AndroidDriver`1..ctor(DesiredCapabilities desiredCapabilities) in c:\AppiumSource\appium-dotnet-driver\appium-dotnet-driver\Appium\Android\AndroidDriver.cs:line 53
   at [NamespaceRemoved].StartDriver(DesiredCapabilities capabilities, String appPath) in c:\[LocationRemoved]\Tools\DriverFactory.cs:line 90
   at ......... Some more non-appium stacktrace

**Comment by TikhomirovSergey** [comment]
The fix was merged. Please wait for a new release. It is coming soon :)

**Comment by alangithubtrader** [comment]
@TikhomirovSergey ,

Is this fix released?

**Comment by Nesaganesh** [comment]
Is this fixed ? anyone please
I am getting the same error having Appium 1.5 and Selenium webdriver 2.48

**Comment by minhhoangvn** [comment]
I got this issue today, i am using Appium 1.5.0.1 and Selenium 2.52
