### ISSUE TITLE
Can't launch application

### ISSUE THREAD

**Issue by mina-thomas** [appium/appium-dotnet-driver#125]
I successfully  connected to webdriver and navigate to url
but I can't launch an application, here is my code:

AppiumDriver<AppiumWebElement> driver;
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("deviceName", "emulator-5554");
capabilities.SetCapability("platformName", "Android");
capabilities.SetCapability("appPackage", "com.android.calculator2");
capabilities.SetCapability("appActivity", "com.android.calculator2.Calculator");
capabilities.SetCapability("noReset", true);

driver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:8080/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
driver.LaunchApp(); 

here is the error 
OpenQA.Selenium.WebDriverException was unhandled
  HResult=-2146233088
  Message=Unexpected error. 
  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1225
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 979
       at OpenQA.Selenium.Appium.AppiumDriver`1.InstallApp(String appPath) in c:\Users\mina.thomas\Downloads\appium-dotnet-driver-master (1)\appium-dotnet-driver-master\appium-dotnet-driver\Appium\AppiumDriver.cs:line 386
       at AppiumTests.AppiumTestSuite.BeforeAll() in c:\Users\mina.thomas\Documents\Visual Studio 2012\Projects\AppiumTests\AppiumTests\Program.cs:line 111
       at AppiumTests.Program.Main(String[] args) in c:\Users\mina.thomas\Documents\Visual Studio 2012\Projects\AppiumTests\AppiumTests\Program.cs:line 135
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by TikhomirovSergey** [comment]
@mina-thomas 
It seems you are doing something wrong. I suggest you to set up capabilities like it is bellow: 

DesiredCapabilities capabilities = new DesiredCapabilities();
apabilities.SetCapability("deviceName", "Android Emulator");
capabilities.SetCapability("platformName", "Android");
capabilities.SetCapability("app", "<Absolute or relative path to your app>");
capabilities.SetCapability("appPackage", "com.android.calculator2");
capabilities.SetCapability("appActivity", "com.android.calculator2.Calculator");
capabilities.SetCapability("noReset", true);

**Comment by TikhomirovSergey** [comment]
There is no conversation
@mina-thomas Please reopen this if it is still actual
