### ISSUE TITLE
Unable to launch Safari on real iPad 

### ISSUE THREAD

**Issue by pshilpa1** [appium/appium-dotnet-driver#143]
I am trying to use Appium to test Selenium webdriver C# scripts on real iPad device.
Getting error that 
Result StackTrace:

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
at UnitTestProject2.UnitTest1.TestMethod1() in C:\ED\TestAutomation\Ed.LMS\Main\UnitTestProject2\UnitTestProject2\UnitTest1.cs:line 29
Result Message: 
Test method UnitTestProject2.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip') (33)

Tried looking for this folder on mac and found it doesn't exist there. Came across this post and tried running ./reset.sh but unable to run ./reset.sh on mac. I already have safarilauncher installed on ipad.
Appium is under Applications and I looked into its content using Show package contents but no clue how to get to this folder contents from Terminal and how to run that command to have a SafariLauncher folder in Appium.../build.

Please help.
I have a valid development profile, provisioning profile on apple developer and my device is registered there too.
I tried updating to Appium1.5, couldn't get the app , so installed it using npm and launch it in Terminal using Appium. Script is giving following error with Appium 1.5
[iOS] Error: Command 'xcodebuild -sdk iphoneos9.2 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:90:13)
    at ChildProcess.emit (events.js:182:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
 [Error: Command 'xcodebuild -sdk iphoneos9.2 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)]
[iOS] Bad app: '/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[MJSONWP] Encountered internal error running command: Error: Bad app: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at IosDriver.configureApp$ (lib/driver.js:229:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

Please help.

Thanks in advance

**Comment by TikhomirovSergey** [comment]
Hi @pshilpa1 
It is not clear what happens. 
Could you provide client code sample and server output as links to gists? 
https://help.github.com/articles/creating-gists/

Did it work with old nodes/iOS 8.x?
Do you work on Windows? 

I'm suspecting that it may be the server side problem. The supporting of iOS 9.x has appered since server node v1.5.0. Something may be raw yet. 

I would advice you to report a bug here too: https://github.com/appium/appium/issues

**Comment by pshilpa1** [comment]
I tried it with Appium1.4.13 and was getting issues with launching safari on ipad , got a suggestion to upgrade to Appium1.5 , I downloaded the source code as couldn't find Appium app for 1.5 and started it from terminal.
I am using Mac , what do you mean by server node v1.5.0? is it to refer Appium on mac.

Having hard time to figure it out, if there is a work around to launch safari on real ipad  with Appium1.4.13 please let me know.
My test script is on Windows machine in VS as following
//AppiumDriver<AppiumWebElement> driver;
            RemoteWebDriver driver;
            DesiredCapabilities capability = new DesiredCapabilities();
            //capability.SetCapability("platform", "iOS");
            capability.SetCapability(MobileCapabilityType.AppiumVersion, "1.5");
            capability.SetCapability(MobileCapabilityType.DeviceName, "iPad4");
            capability.SetCapability("browserName", "safari");
            capability.SetCapability("udid", "e33e369b28dc9Ca48f2e107C15fa75e9399649bf");
            //capability.SetCapability("appPackage", "io.appium.SafariLauncher");
            capability.SetCapability("platformName", "iOS");
            //driver = new IOSDriver<AppiumWebElement>(new Uri("http://10.24.110.69:4723/wd/hub/"),capability);
            driver = new RemoteWebDriver(new Uri("http://10.24.110.69:4723/wd/hub/"), capability);
            //driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub/"), capability);
            driver.Navigate().GoToUrl("https://test4.ple2.plato.com/");

:

**Comment by TikhomirovSergey** [comment]
@pshilpa1 
Have you tried to set target iOS version: 

capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "8.2");

**Comment by pshilpa1** [comment]
tried that but still getting exception for SafariLauncher.zip
Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.iOS.IOSDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
   at UnitTestProject2.UnitTest1.TestMethod1() in C:\ED\TestAutomation\Ed.LMS\Main\UnitTestProject2\UnitTestProject2\AppiumIpad.cs:line 27
Result Message:	
Test method UnitTestProject2.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip') (33)

**Comment by imurchie** [comment]
Unfortunately, running Safari on a real device is an involved process, because of the need to use SafariLauncher to launch it, and the need to build SafariLauncher with your developer identity. The instructions are [here](https://github.com/appium/appium/blob/old-master/docs/en/writing-running-appium/mobile-web.md#mobile-safari-on-a-real-ios-device) for 1.4.

Appium 1.5 automated the building and installing much more seemlessly, in most cases. However there is not yet a bundled Mac app for it.

**Comment by pshilpa1** [comment]
I could install safari Launcher on ipad once but when trying to run my Selenium web driver script its failing with above error.
Safari Launcher is on ipad but not sure when I launch the appium server and run the script from VS2015, does it try to reinstall the SafariLauncher?
Do I need  to specify the path for SafariLauncher.app in Appium App GUI >apple icon> Basic Settings app path? Or Do I need to check mobile safari to run scripts on ipad?

Please help.
Thanks

**Comment by TikhomirovSergey** [comment]
@pshilpa1 
This problem is not related to .Net client. It is most likely the problem of the server. 
 I think you are facing this issue: https://github.com/appium/appium/issues/6230

Thanks for the report. But it can't be resolved on the client side.

**Comment by pshilpa1** [comment]
I tried it with appium 1.5 too but no luck it gives error for bad app for safariLauncher , could you please be more detailed for how to  resolve  it on client side,

**Comment by suganeby** [comment]
@pshilpa1, were you able to fix this issue? I have the bad path issue in appium 1.5.
