### ISSUE TITLE
exception: A new session could not be created. selenium 3.141, appium 4.0.0.2 beta

### ISSUE THREAD

**Issue by nataliya-yatsynych** [appium/appium-dotnet-driver#290]
## Description
I am having an  issue : System.InvalidOperationException: 'A new session could not be created. (SessionNotCreated)'

I am trying to launch windows desktop app using Windows Application Driver with appium

code snippet:
```

            var appCapabilities = new AppiumOptions();
            appCapabilities.AddAdditionalCapability("app", @"C:\Program Files (x86)\myapp.exe\");
            appCapabilities.AddAdditionalCapability("platformName", "Windows");
            appCapabilities.AddAdditionalCapability("deviceName", "WindowsPC");


            Uri UriStr = new Uri("http://127.0.0.1:4723");

            _driver =
                new WindowsDriver<WindowsElement>(UriStr, appCapabilities);
            _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
```

## Environment
.Net 4.6.1
VisualStudio 2017
Appium.WebDriver -Version 4.0.0.2-beta
Selenium WebDriver - 3.141.0  

`System.InvalidOperationException
  HResult=0x80131509
  Message=A new session could not be created. (SessionNotCreated)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(Uri remoteAddress, AppiumOptions AppiumOptions)
   at Tests.CalculatorTests.TestInit() in C:\Users\ny7894\Source\Repos\DesktopSample1\Tests\UnitTest1.cs:line 25
`

**Comment by nataliya-yatsynych** [comment]
not an issue, path to app had special character
