### ISSUE TITLE
Using PageFactory with Appium is failing because DotNetSeleniumExtras.dll cannot be found

### ISSUE THREAD

**Issue by theAshenfire** [appium/appium-dotnet-driver#291]
## Description

I'm trying to use Selenium's PageFactory with AppiumPageObjectMemberDecorator. However, i receive errors when trying to load DotNetSeleniumExtras.dll.

## Environment

* .NET Core v2.1
* Appium 1.9.0
* Appium.Net v4.0.0.3 beta

## Details

In my code there is a copy of `PageFactory` object. I init objects with this `PageFactory` and `AppiumPageObjectMemberDecorator()`. After calling `PageFactory.InitElements()` with the decorator all the properties are populated by proxies as expected. However, when i try to access elements of the page i receive an error that DotNetSeleniumExtras.dll cannot be loaded from folder, even tho it is present next to my program's root dll (a.k.a the dll i am running).

I did some investigating (because i'm dev-friendly :D) and i found the error occurs in `ByFactory.cs` when it called `Assembly.LoadFrom("DotNetSeleniumExtras.dll")`. It seems i need a better way to control searching the DLL.

## Code To Reproduce Issue [ Good To Have ]

Code in runner:
```
			LoginPage loginPage = PageFactory.InitElements<LoginPage>(driver);
			loginPage.Login(name, password);

```

Code in LoginPage:
```
	class LoginPage
	{
		[FindsBy(How = How.Id, Using = "name")]
		private IWebElement nameElement;

		[FindsBy(How = How.Id, Using = "password")]
		private IWebElement passwordElement;

		[FindsBy(How = How.Id, Using = "login")]
		private IWebElement loginElement;

		public bool Displayed => loginElement.Displayed;

		public void TypeName(String name)
		{
			nameElement.SendKeys(name);
		}

		public LoginPage(IWebDriver driver) { }

		public void TypePassword(String password)
		{
			passwordElement.SendKeys(password);
		}

		public void ClickLogin()
		{
			loginElement.Click();
		}

		public void Login(String name, String password)
		{
			TypeName(name);
			TypePassword(password);
			ClickLogin();
		}
```

## Exception stacktraces

_System.IO.FileNotFoundException: Could not load file or assembly '<Private Folder>\SeleniumExtras.PageObjects.dll'. The system cannot find the file specified.
File name: '<Private Folder>\SeleniumExtras.PageObjects.dll'
at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
at System.Reflection.Assembly.LoadFrom(String assemblyFile)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.From(FindsByAttribute attribute)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateDefaultLocatorList(MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateBys(ISearchContext context, MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.AppiumPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
at TestProject.SDK.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
at <Internal code>_

If you need any more information please let me know

**Comment by lanzelot1989** [comment]
Have you tried using 

```
private void SetCurrentDirectoryToTestDirectory()
{
  var testDirectory = TestContext.CurrentContext.TestDirectory;
  Environment.CurrentDirectory = testDirectory;
  Directory.SetCurrentDirectory(testDirectory);
}
```
in a setup class of your unit testing framework?
