### ISSUE TITLE
PageSource returning internal error

### ISSUE THREAD

**Issue by staticcat** [appium/appium-dotnet-driver#313]
## Description

When I call the following:

````
var source = driver.PageSource;
````

I get the following exception:

````
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - ""
````

The Appium server log also returns the following to its console log:

````[HTTP] --> GET /wd/hub/session/359cbf97-fcac-4476-b712-c8b2214c8748/source
[HTTP] {}
[MJSONWP (359cbf97)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/359cbf97-fcac-4476-b712-c8b2214c8748/source' to command name 'getPageSource'[debug] [WD Proxy] Proxying [GET /wd/hub/session/359cbf97-fcac-4476-b712-c8b2214c8748/source] to [GET http://127.0.0.1:4724/wd/hub/session/46BED299-CAD2-4C11-8092-6A1EE4E901D9/source] with body: {}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/46BED299-CAD2-4C11-8092-6A1EE4E901D9/source HTTP/1.1
[WinAppDriver] [STDOUT] Accept: application/json, */*
[WinAppDriver] [STDOUT] Connection: close
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WD Proxy] Got an unexpected response:
[debug] [MJSONWP (359cbf97)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - ""
[debug] [MJSONWP (359cbf97)]     at doJwpProxy (C:\Users\Jason\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:547:13)
[HTTP] <-- GET /wd/hub/session/359cbf97-fcac-4476-b712-c8b2214c8748/source 500 3989 ms - 269
[HTTP]
````

## Environment

- .Net Appium.Net version 4.0.0.5
- Appium version  1.11.0
- Node version v10.15.0
- WinAppDriver version 1.1.1809.18001
- WIndows 10

## Code To Reproduce Issue [ Good To Have ]

````
var source = driver.PageSource;
````

## Exception stacktraces

````
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 500 - ""
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.get_PageSource()
````

## Link to Appium logs

See above

**Comment by KazuCocoa** [comment]
Could you attach the full appium log?

uiautomator2 automation name + newer appium environment helps if your environment is Android 6+ and uiautomator1

**Comment by staticcat** [comment]
This is using the WinAppDriver. Just testing a Windows 10 WinForms/WPF application. 

Not using uiautomator2 or 1 from what I understand about the setup here.

**Comment by akinsolb** [comment]
@staticcat I'm unable to reproduce this. Are you able to try this with appium server v1.12.1 and the latest [beta](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.6-beta)? Also, please create add a gist of the full appium server logs
