### ISSUE TITLE
findElementsFromElement() tries to use CSS selector on 4.0.0.6-beta

### ISSUE THREAD

**Issue by saska123** [appium/appium-dotnet-driver#328]
## Description

When using Appium Page Object pattern and trying to locate chained elements:
FindElementsFromElement command gets translated to a CSS selector which does not work.

## Environment

* .NET client build version: 4.0.0.6-beta
* Appium server version: 1.11.0
* Desktop OS/version used to run Appium: macOS Mojave 10.14.4
* Node.js version: 10.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device LG Nexus 5X

## Details

Used package versions:

Appium.WebDriver: 4.0.0.6-beta
Castle.Core: 4.4.0
Newtonsoft.Json: 12.0.2
Selenium.WebDriver: 3.141.0
Selenium.Support: 3.141.0
DotNetSeleniumExtras.PageObjects: 3.11.0

## Code To Reproduce Issue [ Good To Have ]

```
[MobileFindsBySequence(Android = true, IOS = false)]
[FindsByAndroidUIAutomator(ID = "login_input_flipper")]
[FindsByAndroidUIAutomator(ClassName = "android.widget.TextView")]
protected IMobileElement<AppiumWebElement> LoginOtpInfo;
```
Calling it like:
`enabled = LoginOtpInfo.Enabled;`

## Exception stacktraces

```
OneTimeSetUp: OpenQA.Selenium.NoSuchElementException : Couldn't locate an element by these strategies: Locator map: 
- native content: "By.Chained([By.Id:login_input_flipper,By.ClassName[Contains]: android.widget.TextView]); " 
- html content: "ByIdOrName([LoginOtpInfo]); " 
  ----> OpenQA.Selenium.WebDriverTimeoutException : Timed out after 1 seconds
```

## Link to Appium logs

```
2019-04-30 12:57:58:743 [HTTP] --> POST /wd/hub/session/f2977aba-0179-4c50-b059-dcaf7a8aadb4/elements
2019-04-30 12:57:58:743 [HTTP] {"using":"id","value":"login_input_flipper"}
2019-04-30 12:57:58:744 [W3C (f2977aba)] Calling AppiumDriver.findElements() with args: ["id","login_input_flipper","f2977aba-0179-4c50-b059-dcaf7a8aadb4"]
2019-04-30 12:57:58:744 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2019-04-30 12:57:58:744 [BaseDriver] Waiting up to 0 ms for condition
2019-04-30 12:57:58:745 [WD Proxy] Matched '/elements' to command name 'findElements'
2019-04-30 12:57:58:745 [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8201/wd/hub/session/8aacd558-eca6-4055-91a8-7b306e2c8f50/elements] with body: {"strategy":"id","selector":"login_input_flipper","context":"","multiple":true}
2019-04-30 12:57:58:849 [WD Proxy] Got response with status 200: {"sessionId":"8aacd558-eca6-4055-91a8-7b306e2c8f50","status":0,"value":[{"ELEMENT":"58c86c81-e49d-4318-891b-bd4394dcb8ca"}]}
2019-04-30 12:57:58:850 [W3C (f2977aba)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"58c86c81-e49d-4318-891b-bd4394dcb8ca","ELEMENT":"58c86c81-e49d-4318-891b-bd4394dcb8ca"}]
2019-04-30 12:57:58:851 [HTTP] <-- POST /wd/hub/session/f2977aba-0179-4c50-b059-dcaf7a8aadb4/elements 200 108 ms - 139
2019-04-30 12:57:58:852 [HTTP] 
2019-04-30 12:57:58:860 [HTTP] --> POST /wd/hub/session/f2977aba-0179-4c50-b059-dcaf7a8aadb4/element/58c86c81-e49d-4318-891b-bd4394dcb8ca/elements
2019-04-30 12:57:58:860 [HTTP] {"using":"css selector","value":".android\\.widget\\.TextView"}
2019-04-30 12:57:58:860 [W3C (f2977aba)] Calling AppiumDriver.findElementsFromElement() with args: ["css selector",".android\\.widget\\.TextView","58c86c81-e49d-4318-891b-bd4394dcb8ca","f2977aba-0179-4c50-b059-dcaf7a8aadb4"]
2019-04-30 12:57:58:861 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2019-04-30 12:57:58:869 [W3C (f2977aba)] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at AndroidUiautomator2Driver.validateLocatorStrategy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:344:13)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at AndroidUiautomator2Driver.helpers.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:28:8)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at AndroidUiautomator2Driver.commands.findElementsFromElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:68:21)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at curCommandCancellable._bluebird.default.resolve.then (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:291:18)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
2019-04-30 12:57:58:869 [W3C (f2977aba)]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at runCallback (timers.js:696:18)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at tryOnImmediate (timers.js:667:5)
2019-04-30 12:57:58:870 [W3C (f2977aba)]     at processImmediate (timers.js:649:5)
2019-04-30 12:57:58:871 [HTTP] <-- POST /wd/hub/session/f2977aba-0179-4c50-b059-dcaf7a8aadb4/element/58c86c81-e49d-4318-891b-bd4394dcb8ca/elements 400 11 ms - 2049
```

**Comment by saska123** [comment]
Anyone has an idea how to fix this? I guess this might be related to [FindElementBy<X> tries to use CSS selector on 4.0.0.2-beta](https://github.com/appium/appium-dotnet-driver/issues/265)
