### ISSUE TITLE
Started to get an error: The application at 'com.android.calculator' does not exist or is not accessible

### ISSUE THREAD

**Issue by Ukrainis** [appium/appium-dotnet-driver#384]
## Description

After updating Appium to last version, getting error from title.

## Environment

* Target framework: net core 2.1
* Appium server: 1.15.1
* Desktop OS/version used to run Appium if necessary: Windows 10
* Mobile platform/version under test: Google nexus with Android 5.1.1 and OnePlus5 with Android 9
* Real device or emulator/simulator: real devices

## Details
Some time ago started with Appium. From beginning it was working with previous appium version without PageObjects. After added PageObject was working only tests without them. After updating appium server started to get problem, which is mentioned in title.
## Code To Reproduce Issue [ Good To Have ]

UnitTest1.cs:
```
namespace AppiumPilotProject
{
    public class Tests
    {
        private AndroidDriver<AppiumWebElement> _driver;
        private CalculatorMainPage _calculatorMainPage;
        private AppiumLocalService _appiumLocalService;

        [SetUp]
        public void Setup()
        {
            _appiumLocalService = new AppiumServiceBuilder().UsingAnyFreePort().Build();
            _appiumLocalService.Start();

            DriverOptions caps = new AppiumOptions();
            caps.AddAdditionalCapability(MobileCapabilityType.DeviceName, "Tablet");
            //caps.AddAdditionalCapability(MobileCapabilityType.App, "com.android.calculator2");
            caps.AddAdditionalCapability(MobileCapabilityType.App, "com.oneplus.calculator");
            //caps.AddAdditionalCapability("appActivity", "com.android.calculator2.Calculator");
            caps.AddAdditionalCapability("appActivity", "com.oneplus.calculator.Calculator");
            caps.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            caps.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "9");
            caps.AddAdditionalCapability(MobileCapabilityType.NoReset, true);
            caps.AddAdditionalCapability(MobileCapabilityType.AutomationName, "UiAutomator2");

            //     _driver = new AndroidDriver<AppiumWebElement>(
            //         _appiumLocalService, caps);
            _driver = new AndroidDriver<AppiumWebElement>(
                new Uri("http://127.0.0.1:4723/wd/hub"), caps);

            TimeOutDuration timeSpan = new TimeOutDuration(new TimeSpan(0, 0, 0, 10, 0));

            _calculatorMainPage = new CalculatorMainPage();

            PageFactory.InitElements(_driver, _calculatorMainPage, new AppiumPageObjectMemberDecorator(timeSpan));
        }

        [Test]
        public void PlusTest()
        {
            //_calculatorMainPage = new CalculatorMainPage(_driver);
           // IWebElement firstNumber = _driver.FindElementById("com.android.calculator2:id/digit_5");
          //  firstNumber.Click();
            _calculatorMainPage.Digit5Btn.Click();

           // IWebElement plusButton = _driver.FindElementById("com.android.calculator2:id/op_add");
           // plusButton.Click();
            _calculatorMainPage.PlusBtn.Click();

           // IWebElement secondNumber = _driver.FindElementById("com.android.calculator2:id/digit_9");
          //  secondNumber.Click();
            _calculatorMainPage.Digit2Btn.Click();

           // IWebElement equalsButton = _driver.FindElementById("com.android.calculator2:id/eq");
           // equalsButton.Click();
            _calculatorMainPage.EqualsBtn.Click();
           // IWebElement resultField = _driver.FindElementById("com.android.calculator2:id/formula");
           // var result = resultField.Text;
            var result = _calculatorMainPage.ResultField.Text;

            Assert.AreEqual(14, int.Parse(result));
        }

        [Test]
        public void MinusTest()
        {
            AppiumWebElement firstNumber =
                _driver.FindElementByAndroidUIAutomator("new UiSelector().resourceId(\"android:id/digit_2\")");//FindElementById("com.android.calculator2:id/digit_5");
            firstNumber.Click();

            IWebElement plusButton = _driver.FindElementById("com.android.calculator2:id/op_sub");
            plusButton.Click();

            IWebElement secondNumber = _driver.FindElementById("com.android.calculator2:id/digit_2");
            secondNumber.Click();

            IWebElement equalsButton = _driver.FindElementById("com.android.calculator2:id/eq");
            equalsButton.Click();

            IWebElement resultField = _driver.FindElementById("com.android.calculator2:id/formula");
            var result = resultField.Text;

            Assert.AreEqual(3, int.Parse(result));
        }

        [Test]
        public void MultipleTest()
        {
            IWebElement firstNumber = _driver.FindElementById("com.android.calculator2:id/digit_5");
            firstNumber.Click();

            IWebElement plusButton = _driver.FindElementById("com.android.calculator2:id/op_mul");
            plusButton.Click();

            IWebElement secondNumber = _driver.FindElementById("com.android.calculator2:id/digit_9");
            secondNumber.Click();

            IWebElement equalsButton = _driver.FindElementById("com.android.calculator2:id/eq");
            equalsButton.Click();

            IWebElement resultField = _driver.FindElementById("com.android.calculator2:id/formula");
            var result = resultField.Text;

            Assert.AreEqual(45, int.Parse(result));
        }
        // com.android.calculator2:id/op_mul

        [TearDown]
        public void AfterTest()
        {
            _driver.Quit();
            _appiumLocalService.Dispose();
        }
    }
}
```

CalculatorMainPage.cs:
```
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Interfaces;
using OpenQA.Selenium.Appium.PageObjects.Attributes;

namespace AppiumPilotProject
{
    public class CalculatorMainPage
    {
        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/digit_2")]
        public IMobileElement<AndroidElement> Digit2Btn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/digit_5")]
        public IMobileElement<AndroidElement> Digit5Btn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/digit_9")]
        public IMobileElement<AndroidElement> Digit9Btn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/op_add")]
        public IMobileElement<AndroidElement> PlusBtn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/op_sub")]
        public IMobileElement<AndroidElement> MinusBtn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/op_mul")]
        public IMobileElement<AndroidElement> MultiplyBtn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/eq")]
        public IMobileElement<AndroidElement> EqualsBtn { get; set; }

        [FindsByAndroidUIAutomator(Accessibility = "com.android.calculator2:id/eq")]
        public IMobileElement<AndroidElement> ResultField { get; set; }

    }
}
```

## Exception stacktraces
Result StackTrace:	
```
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities appiumOptions)
   at AppiumPilotProject.Tests.Setup() in D:\c#_projects\AppiumPilotProject\AppiumPilotProject\UnitTest1.cs:line 38
--TearDown
   at AppiumPilotProject.Tests.AfterTest() in D:\c#_projects\AppiumPilotProject\AppiumPilotProject\UnitTest1.cs:line 121
Result Message:	
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: The application at 'com.oneplus.calculator' does not exist or is not accessible
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
```

## Link to Appium logs

[gist](https://gist.github.com/Ukrainis/82424f7dccc791e6362ad89f5f2fcdae)

**Comment by mykola-mokhnach** [comment]
you use noReset option, which means Appium expects the app with given identifier to be already present on the device. Such error means the app has been removed from the device or cannot be found.

**Comment by Ukrainis** [comment]
This is basic android calculator, which present. Tried without this capability - got the same.

**Comment by mykola-mokhnach** [comment]
> "appium:app": "com.oneplus.calculator",

`app` capability must contain the full path to the app or an url. Application package name should be set as appPackage cap

**Comment by Ukrainis** [comment]
> 
> 
> > "appium:app": "com.oneplus.calculator",
> 
> `app` capability must contain the full path to the app or an url. Application package name should be set as appPackage cap

But why it was working earlier? Then which should be correct path for Calculator?

**Comment by Ukrainis** [comment]
@mykola-mokhnach , thanks. 
After changed `MobileCapabilityType.App` to `appPackage ` aplication again started to run. Now I have only a problem that elements in PageObject are not found(
