### ISSUE TITLE
Cannot record screen on iOS devices when video type is specified

### ISSUE THREAD

**Issue by saska123** [appium/appium-dotnet-driver#404]
## Description

I am trying to record a test execution on real iOS device. While experimenting with recording settings I found that if I specify any video type - the record will fail. If I do not specify any recording video type (then it defaults to mp4) it will succeed.

## Environment

* .NET client build version: 4.1.1
* Appium server version: 1.15.1
* Desktop OS/version used to run Appium if necessary: macOS Catalina 10.15.2
* Node.js version: 12.14.1
* Mobile platform/version under test: real device - iPhone X, iOS 13.3

## Details

Try specifying mp4:
```
Driver.Instance.StartRecordingScreen(
    IOSStartScreenRecordingOptions.GetIosStartScreenRecordingOptions()
        .WithVideoType(IOSStartScreenRecordingOptions.VideoType.MP4));
```
Error in Appium:
```
2020-04-20 12:34:42:037 [ffmpeg] ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
2020-04-20 12:34:42:038 [ffmpeg]   built with Apple clang version 11.0.0 (clang-1100.0.33.17)
2020-04-20 12:34:42:038 [ffmpeg]   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
2020-04-20 12:34:42:038 [ffmpeg] 
2020-04-20 12:34:42:038 [ffmpeg]   libavutil      56. 31.100 / 56. 31.100
2020-04-20 12:34:42:039 [ffmpeg]   libavcodec     58. 54.100 / 58. 54.100
2020-04-20 12:34:42:039 [ffmpeg]   libavformat    58. 29.100 / 58. 29.100
2020-04-20 12:34:42:039 [ffmpeg]   libavdevice    58.  8.100 / 58.  8.100
2020-04-20 12:34:42:039 [ffmpeg]   libavfilter     7. 57.100 /  7. 57.100
2020-04-20 12:34:42:039 [ffmpeg]   libavresample   4.  0.  0 /  4.  0.  0
2020-04-20 12:34:42:039 [ffmpeg]   libswscale      5.  5.100 /  5.  5.100
2020-04-20 12:34:42:039 [ffmpeg]   libswresample   3.  5.100 /  3.  5.100
2020-04-20 12:34:42:040 [ffmpeg]   libpostproc    55.  5.100 / 55.  5.100
2020-04-20 12:34:42:040 [ffmpeg] 
2020-04-20 12:34:42:232 [ffmpeg] Input #0, mjpeg, from 'http://localhost:9100':
2020-04-20 12:34:42:232 [ffmpeg]   Duration: N/A, bitrate: N/A
2020-04-20 12:34:42:232 [ffmpeg] 
2020-04-20 12:34:42:233 [ffmpeg]     Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1125x2436 [SAR 216:216 DAR 375:812], 25 tbr, 1200k tbn, 25 tbc
2020-04-20 12:34:42:233 [ffmpeg] Unknown encoder 'mp4'
2020-04-20 12:34:42:233 [ffmpeg] 
2020-04-20 12:34:42:235 [iProxy@36fad...] Error: read ECONNRESET
2020-04-20 12:34:42:235 [iProxy@36fad...]     at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
2020-04-20 12:34:47:040 [XCUITest] Screen capture process did not start within 5000ms. Continuing anyway
2020-04-20 12:34:47:040 [DevCon Factory] Releasing connections for 36fadaa9cb9516ba18bd0a7e764b8369fef568b6 device on 9100 port number
2020-04-20 12:34:47:041 [DevCon Factory] Found cached connections to release: ["36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100"]
2020-04-20 12:34:47:041 [DevCon Factory] Releasing the listener for '36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100'
2020-04-20 12:34:47:042 [DevCon Factory] Cached connections count: 1
2020-04-20 12:34:47:053 [W3C (90f39573)] Encountered internal error running command: Error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details
2020-04-20 12:34:47:053 [W3C (90f39573)]     at ScreenRecorder.start (/Users/bc9667/.nvm/versions/node/v12.14.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/recordscreen.js:114:13)
2020-04-20 12:34:47:062 [HTTP] <-- POST /wd/hub/session/90f39573-e3a0-4eb2-a586-b178bf710ff6/appium/start_recording_screen 500 5244 ms - 737
```
Try specifying H264:
```
Driver.Instance.StartRecordingScreen(
    IOSStartScreenRecordingOptions.GetIosStartScreenRecordingOptions()
        .WithVideoType(IOSStartScreenRecordingOptions.VideoType.H264));
```
Error in Appium:
```
2020-04-20 12:15:02:108 [ffmpeg] ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
2020-04-20 12:15:02:108 [ffmpeg]   built with Apple clang version 11.0.0 (clang-1100.0.33.17)
2020-04-20 12:15:02:109 [ffmpeg]   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
2020-04-20 12:15:02:109 [ffmpeg] 
2020-04-20 12:15:02:109 [ffmpeg]   libavutil      56. 31.100 / 56. 31.100
2020-04-20 12:15:02:109 [ffmpeg]   libavcodec     58. 54.100 / 58. 54.100
2020-04-20 12:15:02:110 [ffmpeg]   libavformat    58. 29.100 / 58. 29.100
2020-04-20 12:15:02:110 [ffmpeg]   libavdevice    58.  8.100 / 58.  8.100
2020-04-20 12:15:02:110 [ffmpeg]   libavfilter     7. 57.100 /  7. 57.100
2020-04-20 12:15:02:110 [ffmpeg]   libavresample   4.  0.  0 /  4.  0.  0
2020-04-20 12:15:02:110 [ffmpeg]   libswscale      5.  5.100 /  5.  5.100
2020-04-20 12:15:02:110 [ffmpeg]   libswresample   3.  5.100 /  3.  5.100
2020-04-20 12:15:02:111 [ffmpeg]   libpostproc    55.  5.100 / 55.  5.100
2020-04-20 12:15:02:111 [ffmpeg] 
2020-04-20 12:15:02:304 [ffmpeg] Input #0, mjpeg, from 'http://localhost:9100':
2020-04-20 12:15:02:305 [ffmpeg]   Duration: N/A, bitrate: N/A
2020-04-20 12:15:02:305 [ffmpeg] 
2020-04-20 12:15:02:305 [ffmpeg]     Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1125x2436 [SAR 216:216 DAR 375:812], 25 tbr, 1200k tbn, 25 tbc
2020-04-20 12:15:02:305 [ffmpeg] Stream mapping:
2020-04-20 12:15:02:306 [ffmpeg]   Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
2020-04-20 12:15:02:306 [ffmpeg] Press [q] to stop, [?] for help
2020-04-20 12:15:02:306 [ffmpeg] 
2020-04-20 12:15:02:316 [ffmpeg] [libx264 @ 0x7f9ed3804600] width not divisible by 2 (1125x2436)
2020-04-20 12:15:02:317 [ffmpeg] 
2020-04-20 12:15:02:317 [ffmpeg] Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2020-04-20 12:15:02:317 [ffmpeg] Conversion failed!
2020-04-20 12:15:02:317 [ffmpeg] 
2020-04-20 12:15:02:318 [iProxy@36fad...] Error: read ECONNRESET
2020-04-20 12:15:02:318 [iProxy@36fad...]     at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
2020-04-20 12:15:07:093 [XCUITest] Screen capture process did not start within 5000ms. Continuing anyway
2020-04-20 12:15:07:094 [DevCon Factory] Releasing connections for 36fadaa9cb9516ba18bd0a7e764b8369fef568b6 device on 9100 port number
2020-04-20 12:15:07:094 [DevCon Factory] Found cached connections to release: ["36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100"]
2020-04-20 12:15:07:095 [DevCon Factory] Releasing the listener for '36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100'
2020-04-20 12:15:07:096 [DevCon Factory] Cached connections count: 1
2020-04-20 12:15:07:110 [W3C (e309ece2)] Encountered internal error running command: Error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details
2020-04-20 12:15:07:110 [W3C (e309ece2)]     at ScreenRecorder.start (/Users/bc9667/.nvm/versions/node/v12.14.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/recordscreen.js:114:13)
2020-04-20 12:15:07:119 [HTTP] <-- POST /wd/hub/session/e309ece2-c48a-4c70-a291-cff8929e55a9/appium/start_recording_screen 500 5230 ms - 737
```
Try specifying FMP4:
```
Driver.Instance.StartRecordingScreen(
    IOSStartScreenRecordingOptions.GetIosStartScreenRecordingOptions()
        .WithVideoType(IOSStartScreenRecordingOptions.VideoType.FMP4));
```
Error in Appium:
```
2020-04-20 12:37:46:393 [ffmpeg] ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
2020-04-20 12:37:46:393 [ffmpeg]   built with Apple clang version 11.0.0 (clang-1100.0.33.17)
2020-04-20 12:37:46:393 [ffmpeg]   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
2020-04-20 12:37:46:393 [ffmpeg] 
2020-04-20 12:37:46:394 [ffmpeg]   libavutil      56. 31.100 / 56. 31.100
2020-04-20 12:37:46:394 [ffmpeg]   libavcodec     58. 54.100 / 58. 54.100
2020-04-20 12:37:46:394 [ffmpeg]   libavformat    58. 29.100 / 58. 29.100
2020-04-20 12:37:46:394 [ffmpeg]   libavdevice    58.  8.100 / 58.  8.100
2020-04-20 12:37:46:394 [ffmpeg]   libavfilter     7. 57.100 /  7. 57.100
2020-04-20 12:37:46:394 [ffmpeg]   libavresample   4.  0.  0 /  4.  0.  0
2020-04-20 12:37:46:394 [ffmpeg]   libswscale      5.  5.100 /  5.  5.100
2020-04-20 12:37:46:394 [ffmpeg]   libswresample   3.  5.100 /  3.  5.100
2020-04-20 12:37:46:395 [ffmpeg]   libpostproc    55.  5.100 / 55.  5.100
2020-04-20 12:37:46:395 [ffmpeg] 
2020-04-20 12:37:46:644 [ffmpeg] Input #0, mjpeg, from 'http://localhost:9100':
2020-04-20 12:37:46:644 [ffmpeg]   Duration: N/A, bitrate: N/A
2020-04-20 12:37:46:644 [ffmpeg] 
2020-04-20 12:37:46:645 [ffmpeg]     Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1125x2436 [SAR 216:216 DAR 375:812], 25 tbr, 1200k tbn, 25 tbc
2020-04-20 12:37:46:645 [ffmpeg] Unknown encoder 'fmp4'
2020-04-20 12:37:46:645 [ffmpeg] 
2020-04-20 12:37:46:646 [iProxy@36fad...] Error: read ECONNRESET
2020-04-20 12:37:46:646 [iProxy@36fad...]     at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
2020-04-20 12:37:51:446 [XCUITest] Screen capture process did not start within 5000ms. Continuing anyway
2020-04-20 12:37:51:446 [DevCon Factory] Releasing connections for 36fadaa9cb9516ba18bd0a7e764b8369fef568b6 device on 9100 port number
2020-04-20 12:37:51:446 [DevCon Factory] Found cached connections to release: ["36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100"]
2020-04-20 12:37:51:447 [DevCon Factory] Releasing the listener for '36fadaa9cb9516ba18bd0a7e764b8369fef568b6:9100'
2020-04-20 12:37:51:448 [DevCon Factory] Cached connections count: 1
2020-04-20 12:37:51:458 [W3C (dedc9607)] Encountered internal error running command: Error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details
2020-04-20 12:37:51:458 [W3C (dedc9607)]     at ScreenRecorder.start (/Users/bc9667/.nvm/versions/node/v12.14.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/recordscreen.js:114:13)
2020-04-20 12:37:51:467 [HTTP] <-- POST /wd/hub/session/dedc9607-9b06-48ad-8011-7feda39c53cf/appium/start_recording_screen 500 5257 ms - 737
```

**Comment by mykola-mokhnach** [comment]
> 2020-04-20 12:15:02:316 [ffmpeg] [libx264 @ 0x7f9ed3804600] width not divisible by 2 (1125x2436)

I think ffmpeg prints a pretty clear error message

**Comment by saska123** [comment]
> > 2020-04-20 12:15:02:316 [ffmpeg] [libx264 @ 0x7f9ed3804600] width not divisible by 2 (1125x2436)
> 
> I think ffmpeg prints a pretty clear error message

So why am I getting this? My device is incompatible because of screen size?

Also shouldn't I be able to specify different video formats? According to [this post](https://github.com/appium/appium/issues/11276#issuecomment-498698062) mpeg4 should be available format. Or its the same as H264? Im not quite experienced with video formats...

**Comment by KazuCocoa** [comment]
It is because of ffmpeg limitation. `scale=trunc(iw/2)*2:trunc(ih/2)*2` as `videoScale` parameter may work.
https://github.com/appium/appium/issues/12856#issuecomment-523829905
https://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/

**Comment by saska123** [comment]
> It is because of ffmpeg limitation. `scale=trunc(iw/2)*2:trunc(ih/2)*2` as `videoScale` parameter may work.
> [appium/appium#12856 (comment)](https://github.com/appium/appium/issues/12856#issuecomment-523829905)
> https://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/

Unfortunately videoScale parameter is not implemented - [Screen recording options not implemented?](https://github.com/appium/appium-dotnet-driver/issues/400#issue-589007412)

**Comment by KazuCocoa** [comment]
Okay, then, this client needs it first

**Comment by kkallu** [comment]
Hi @KazuCocoa @mykola-mokhnach 
Can you please help me with below error message ,

FAILED CONFIGURATION: @BeforeMethod createDriver
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command ''C:\\Users\\karthik kallu\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s be716809 shell kill -15 2810' exited with code 1'; Stderr: '/system/bin/sh: kill: 2810: Operation not permitted'; Code: '1'

Here is my code:
in before method 
        ((CanRecordScreen)driver).startRecordingScreen();
in After method
String media=((CanRecordScreen)driver).stopRecordingScreen();
		String dir="TestResults";
		File TestResultsDir=new File(dir);
		if(!TestResultsDir.exists())
		{
			TestResultsDir.mkdirs();
		}
		FileOutputStream stream;
		try {
			stream = new FileOutputStream(TestResultsDir+File.separator+"TestCase_"+GenerateRandomString.generateRandomNumber()+".mp4");
			stream.write(Base64.decodeBase64(media));
		} catch (FileNotFoundException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
         catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		driver.quit();

Thanks in advance.

**Comment by KazuCocoa** [comment]
`C:\Users\karthik kallu\AppData\Local\Android\Sdk\platform-tools\adb.exe' -P 5037 -s be716809 shell kill -15 2810`
The adb command had trouble. Potentially, other versions of platform-tools could resolve it...

btw, yours is on Android. Not iOS as this issue topic.

**Comment by kkallu** [comment]
Sorry for that ,i delete it ,'
Thanks.
