### ISSUE TITLE
[FindsByIOSUIAutomation] [FindsByAndroidUIAutmator] attributes is not working in Appium c# mobile automation

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium-dotnet-driver#436]
## The problem

I a have a native application supported in both android and IOS platform. I am trying to build a common code to automate the on both the IOS and Android platform. But when identifying one Cancel button by accessbility id= cancel using the below code giving null value. Can you please let me know the issue in this.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.91.
* Last Appium version that did not exhibit the issue (if applicable): All it exibited
* Desktop OS/version used to run Appium: Mac Cataline 10.15.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 13.2.3
* Real device or emulator/simulator: Real Iphone device
* Appium CLI or Appium.app|exe:

## Details

Can you please help me with sample C# with appium  sample code base to start the automation

## Link to Appium logs

Screenshot of the element declared
![image](https://user-images.githubusercontent.com/24207575/93584849-8562b900-f9c3-11ea-9292-e510bab917b8.png)

**Comment by akinsolb** [comment]
So just to be clear on your problem, from observing the below property 
`public List<IWebElement> ConfirmationPopUpCancel`
you are looking for a list of views with the accessibility id =Cancel?

Can you upload a [gist](https://gist.github.com) of your server log?

**Comment by podupu** [comment]
<ItemGroup>
    <PackageReference Include="Appium.WebDriver" Version="4.2.1" />
    <PackageReference Include="DotNetSeleniumExtras.PageObjects" Version="3.11.0" />
    <PackageReference Include="DotNetSeleniumExtras.PageObjects.Core" Version="3.12.0" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="Selenium.Support" Version="3.141.0" />
  </ItemGroup>

 public class Welcome 
    {
        public Welcome(AppiumDriver<AppiumWebElement> _d)
        {
            PageFactory.InitElements(_d, this, new AppiumPageObjectMemberDecorator(Helpers.Env.timeSpan));
        }
        
        
        [FindsByAndroidUIAutomator(ID = "mobile.develop:id/versionTextView")]
        [FindsByIOSUIAutomation(ID = "welcome.label.version")] //this locator will be used                                                                     
        // [FindsBy(How = How.Id, Using = "mobile.develop:id/versionTextView")]
        public IMobileElement<AppiumWebElement> MyElement { get; set; }

    }

Error Message:
   OpenQA.Selenium.NoSuchElementException : Couldn't locate an element by these strategies: Locator map: 
- native content: "By.Id: <MyElement>k__BackingField; " 
- html content: "ByIdOrName([<MyElement>k__BackingField]); " 
  ----> OpenQA.Selenium.WebDriverTimeoutException : Timed out after 5 seconds
  Stack Trace:
     at OpenQA.Selenium.Appium.PageObjects.Interceptors.ElementInterceptor.getTarget(IInvocation ignored)
   at OpenQA.Selenium.Appium.PageObjects.Interceptors.SearchingInterceptor.Intercept(IInvocation invocation)
   at OpenQA.Selenium.Appium.PageObjects.Interceptors.ElementInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IMobileElement`1Proxy.Click()
   at cfs.mobile.ui.auto.firstnet.Test.Test1() in ..
UnitTest1.cs:line 274
--WebDriverTimeoutException
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at OpenQA.Selenium.Appium.PageObjects.Interceptors.ElementInterceptor.getTarget(IInvocation ignored)

**Comment by podupu** [comment]
Fixed by using AppiumWebElement

public HomePage(DriverContext driverContext)
            : base(driverContext)
        {
            PageFactory.InitElements(driverContext.Driver, this, new AppiumPageObjectMemberDecorator(timeSpan));
        }

        TimeOutDuration timeSpan = new TimeOutDuration(new TimeSpan(0, 0, 0, 5, 0));

        [FindsByAndroidUIAutomator(ID = "versionTextView")]
        [FindsByIOSUIAutomation(Accessibility = "welcome.label.version")]
        **private IMobileElement<AppiumWebElement> version { set; get; }**

        public void ClickVersion()
        {
            version.Click();
        }

**Comment by namilkimfree** [comment]
How to fix?
I am using appiumwebelement but not found
