### ISSUE TITLE
Android driver - GetSettings: 'NotYetImplementedError: Method has not yet been implemented'

### ISSUE THREAD

**Issue by gosr** [appium/appium-dotnet-driver#493]
## Description

I'm trying to access 'Settings' of the Android driver in my .NET code. I'm using the latest version (4.3.1) of Appium.WebDriver.
The purpose of access settings (if it matters) is that I need to update the driver to 'compose' (with reference to https://github.com/appium/appium-espresso-driver#jetpack-compose-support).

`var currentDriver = driver.Settings["driver"];` results in:

> System.NotImplementedException : Method has not yet been implemented
  at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError (OpenQA.Selenium.Remote.Response errorResponse) [0x000dc] in <19027cc8501444099501b87290061165>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver.Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x0003d] in <19027cc8501444099501b87290061165>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W].Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x00000] in <7a9e53e0f0754367b36cb9234afdb018>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W].OpenQA.Selenium.Appium.Interfaces.IExecuteMethod.Execute (System.String driverCommand) [0x00000] in <7a9e53e0f0754367b36cb9234afdb018>:0 
  at OpenQA.Selenium.Appium.Android.AndroidCommandExecutionHelper.GetSettings (OpenQA.Selenium.Appium.Interfaces.IExecuteMethod executeMethod) [0x00000] in <7a9e53e0f0754367b36cb9234afdb018>:0 
  at OpenQA.Selenium.Appium.Android.AndroidDriver`1[W].get_Settings () [0x00000] in <7a9e53e0f0754367b36cb9234afdb018>:0

Logs from the server:

> 2022-04-21 11:29:41:181 [HTTP] --> GET /wd/hub/session/8cfb9c8e-b45c-4cbb-97b1-c47ded47bd71/appium/settings
2022-04-21 11:29:41:181 [HTTP] {}
2022-04-21 11:29:41:189 [W3C (8cfb9c8e)] Calling AppiumDriver.getSettings() with args: ["8cfb9c8e-b45c-4cbb-97b1-c47ded47bd71"]
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)]     at EspressoDriver.getSettings (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/appium-espresso-driver/lib/commands/general.js:288:9)
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)]     at commandExecutor (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)]     at /Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:129:12
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)]     at AsyncLock._promiseTry (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:253:31)
2022-04-21 11:29:41:248 [W3C (8cfb9c8e)]     at exec (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:128:9)
2022-04-21 11:29:41:283 [W3C (8cfb9c8e)]     at AsyncLock.acquire (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:144:3)
2022-04-21 11:29:41:283 [W3C (8cfb9c8e)]     at EspressoDriver.executeCommand (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:347:39)
2022-04-21 11:29:41:283 [W3C (8cfb9c8e)]     at AppiumDriver.executeCommand (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/lib/appium.js:547:36)
2022-04-21 11:29:41:284 [W3C (8cfb9c8e)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-04-21 11:29:41:284 [W3C (8cfb9c8e)]     at asyncHandler (/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
2022-04-21 11:29:41:285 [HTTP] <-- GET /wd/hub/session/8cfb9c8e-b45c-4cbb-97b1-c47ded47bd71/appium/settings 405 104 ms - 1525

**Comment by mykola-mokhnach** [comment]
Are you sure you use Appium2 along with the most recent driver version?

**Comment by gosr** [comment]
I am using appium 1.22.3 installed via `npm install -g appium`. When running `npm -g list | grep appium-espresso-driver` I see version 1.45.3. So how can I upgrade the espresso driver to 1.50.1 for example, or even 2.2.1 which seems to be the latest.

**Comment by mykola-mokhnach** [comment]
It is only available with Appium2. Check https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli for more details.

**Comment by arminzukic** [comment]
@mykola-mokhnach It seems the Settings API is only available to the iOS driver as part of the implementation with this pr: https://github.com/appium/appium-dotnet-driver/pull/466 
v5.0.0-alpha2

**Comment by gosr** [comment]
> It is only available with Appium2. Check https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli for more details.

Thanks, I've changed to Appium2.
