### ISSUE TITLE
NullReferenceException in AndroidDriver.ctor

### ISSUE THREAD

**Issue by al007** [appium/appium-dotnet-driver#92]
I use Appium server running on Mac machine and AppiumDriver with c# bindings to execute tests from Windows machine. The issue is that when I create an instance of AndroidDriver its ctor rises a NullReferenceException. When I create an instance of RemoteWebDriver, it works smoothly. This is my code:

```
var caps = new DesiredCapabilities();
caps.SetCapability(MobileCapabilityType.DeviceName, "a0d86205");
caps.SetCapability("udid", "a0d86205");
caps.SetCapability(MobileCapabilityType.App, "https://valid/path/to/my.apk");
caps.SetCapability(MobileCapabilityType.PlatformName, MobilePlatform.Android);

var drv = new AndroidDriver(ServerUri, caps) // rises exception
// var drv = new RemoteWebDriver(ServerUri, caps) // works smoothly
```

Exception:
```
System.NullReferenceException : Object reference not set to an instance of an object.
Result StackTrace:  
at OpenQA.Selenium.Appium.AppiumDriver._AddAppiumCommands()
at OpenQA.Selenium.Appium.AppiumDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Appium.Android.AndroidDriver..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
```

Most recent server responce
```
info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"udid":"a0d86205","deviceName":"a0d86205","platformName":"Android","app":"https://valid/path/to/my.apk"},"udid":"a0d86205","deviceName":"a0d86205","platformName":"Android","app":"https://valid/path/to/my.apk"},"sessionId":"9536382e-a320-4d8b-b8cd-3afdd4c0bd68"}
info: <-- GET /wd/hub/session/9536382e-a320-4d8b-b8cd-3afdd4c0bd68 200 0.702 ms - 641 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"udid":"a0d86205","deviceName":"a0d86205","platformName":"Android","app":"https://valid/path/to/my.apk"},"udid":"a0d86205","deviceName":"a0d86205","platformName":"Android","app":"https://valid/path/to/my.apk"},"sessionId":"9536382e-a320-4d8b-b8cd-3afdd4c0bd68"}
```

Where am I wrong? Why the constructor of AndroidDriver rises this execption and doesn't specify the reason?

**Comment by Astro03** [comment]
try using the new driver i'm about to publish.  I just tried it with your exact settings above and I did not get an error  on construction.
